name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ci:

    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        projectDir: [ "ui", "." ]

    steps:

    - uses: "actions/checkout@v4"
      with:
        submodules: "true"

    - uses: "actions/setup-node@v4"
      with:
        cache: "yarn"

    - name: "Test"
      run: |
        cd "${{ matrix.projectDir }}"
        yarn install --frozen-lockfile
        yarn test

