# This workflow is run whenever a new release is created
# It will make a production build of [ui], and then publish the build to GitHub Pages

name: "Release"
on:
  release:
    types: [ "created" ]

jobs:

  deploy:

    runs-on: "ubuntu-latest"

    permissions:
      contents: write

    steps:

    - uses: "actions/checkout@v4"
      with:
        submodules: "true"

    - uses: "actions/setup-node@v3"
      with:
        cache: "yarn"

    - name: "Build"
      run: |
        cd ui
        yarn install --frozen-lockfile
        yarn build

    - name: "Deploy"
      uses: "peaceiris/actions-gh-pages@v3"
      with:
        github_token: "${{ secrets.GITHUB_TOKEN }}"
        publish_dir: "ui/dist"
